In [1]:
# its used for working on nD arrays

In [2]:
import numpy as np

In [3]:
a1=np.array([1,2,3])# 1D

In [16]:
a2=np.array([[1,2,3],[4,5,6]]) # 2D

In [17]:
a3=np.array([[[1,2,3],[4,5,6]],[[5,6,7],[7,8,6]],[[8,9,7],[8,5,6]]]) #3D

In [23]:
a1


array([1, 2, 3])

In [27]:
a1.shape

(3,)

In [24]:
a2


array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a2.shape

(2, 3)

In [20]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 6, 7],
        [7, 8, 6]],

       [[8, 9, 7],
        [8, 5, 6]]])

In [26]:
a3.shape

(3, 2, 3)

In [32]:
a3[2,0,2]

7

In [33]:
a1.ndim,a2.ndim,a3.ndim  #each a1,a2,a3 are which dimensions

(1, 2, 3)

In [34]:
a2.dtype

dtype('int64')

In [35]:
type(a1)

numpy.ndarray

In [51]:
import pandas as x
y=x.Series([1,2,3])
y

0    1
1    2
2    3
dtype: int64

In [52]:
y.dtype

dtype('int64')

In [53]:
test = [2,1,2]

In [54]:
type(test)

list

In [78]:
np.random.seed(0)
np_array=np.random.randint(100,size=(5,3))
np_array

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88],
       [88, 12, 58]])

In [79]:
import pandas as pd
df = pd.DataFrame(np_array,columns=['x','y','z'])

In [80]:
df

x   y   z
0  44  47  64
1  67  67   9
2  83  21  36
3  87  70  88
4  88  12  58

In [81]:
np.ones((100,100))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [82]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [83]:
a5=np.array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88],
       [88, 12, 58]])

In [84]:
a5

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88],
       [88, 12, 58]])

In [90]:
z = a5[0]
z

array([44, 47, 64])

In [92]:
a5[1:3,1:3]  # 1 at the first shows the second row : 3 is for the 3rd row(here one value greater than the required is needed, second 1 is the second column likethe row : 3 works a value larger than the position as it have 0 1 2 position in first and after : it will be 1 2 3 )

array([[67,  9],
       [21, 36]])

In [99]:
a5.T

array([[44, 67, 83, 87, 88],
       [47, 67, 21, 70, 12],
       [64,  9, 36, 88, 58]])